name: my-first-action
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome message
        run: echo "Hello World!!!!!!!!!!!"
      - name: print Exit message
        run: echo "Good Bye World!!!!"
      - name: print in python env
        run:  python -c 'print("I am 30 years old")'
      - name: print multiple msges
        run: |
              echo "First output"
              echo "Second output"

